// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IActionSystem {
  function gnomik_action_callAction(bytes32 _name, address _target) external;
}
