// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMushroomSystem {
  function gnomik_mushroom_produce() external;

  function gnomik_mushroom_eat() external;
}
