/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    ActionTable: (() => {
      const tableId = new TableId("gnomik", "ActionTable");
      return defineComponent(
        world,
        {
          costAmount1: RecsType.BigInt,
          costAmount2: RecsType.BigInt,
          selfTarget: RecsType.Boolean,
          resultAmount: RecsType.BigInt,
          costResource1: RecsType.String,
          costResource2: RecsType.String,
          costFunction: RecsType.String,
          resultResource: RecsType.String,
          resultFunction: RecsType.String,
          resultType: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ResourceTable: (() => {
      const tableId = new TableId("gnomik", "ResourceTable");
      return defineComponent(
        world,
        {
          value: RecsType.BigInt,
          lastTimeUpdated: RecsType.BigInt,
          rate: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
